name: blepharoplasty
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  mime: ^2.0.0
  talker_dio_logger: ^4.3.4
  logger: ^2.4.0
  ansicolor: ^2.0.2
  iconsax_plus: ^1.0.0
  image_picker: ^1.1.2
  flutter_image_compress: ^3.0.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

 
